name: Security CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  syft:
    name: Generate SBOM (Syft)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Generate SBOM
        run: syft dir:. -o json > sbom.json

  semgrep:
    name: Static Analysis (Semgrep)
    runs-on: ubuntu-latest
    needs: syft
    steps:
      - uses: actions/checkout@v3
      - uses: returntocorp/semgrep-action@v1
        with:
          config: 'p/ci'

  gitleaks:
    name: Secrets Scan (Gitleaks)
    runs-on: ubuntu-latest
    needs: semgrep
    steps:
      - uses: actions/checkout@v3
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml

  zap_scan:
    name: DAST (OWASP ZAP)
    runs-on: ubuntu-latest
    needs: gitleaks
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'https://juice-shop-demo.onrender.com'
